# Generated by Django 5.2.6 on 2025-09-30 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="experience_years",
            field=models.IntegerField(
                default=0, help_text="Years of teaching experience"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="specialization",
            field=models.CharField(
                blank=True, help_text="Area of specialization", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="availability",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="SubjectAllocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                (
                    "allocation_reason",
                    models.CharField(
                        help_text="Why was this teacher assigned this subject",
                        max_length=200,
                    ),
                ),
                (
                    "teacher_satisfaction",
                    models.IntegerField(
                        default=5, help_text="Teacher satisfaction (1-10)"
                    ),
                ),
                (
                    "student_feedback",
                    models.FloatField(
                        blank=True, help_text="Average student rating", null=True
                    ),
                ),
                (
                    "meeting_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the allocation meeting"
                    ),
                ),
                (
                    "was_voluntary",
                    models.BooleanField(
                        default=True, help_text="Did teacher volunteer or was assigned"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable_app.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable_app.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-semester"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSubjectPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            (
                                "preferred",
                                "Preferred - Teacher wants to teach this subject",
                            ),
                            ("willing", "Willing - Teacher can teach this subject"),
                            (
                                "reluctant",
                                "Reluctant - Teacher prefers not to teach but can if needed",
                            ),
                            (
                                "refused",
                                "Refused - Teacher refuses to teach this subject",
                            ),
                            (
                                "unavailable",
                                "Unavailable - Teacher cannot teach this subject",
                            ),
                        ],
                        default="willing",
                        max_length=20,
                    ),
                ),
                (
                    "competency",
                    models.CharField(
                        choices=[
                            ("expert", "Expert - Highly qualified and experienced"),
                            ("proficient", "Proficient - Qualified and capable"),
                            ("basic", "Basic - Can teach but limited experience"),
                            ("learning", "Learning - New to this subject"),
                            ("unqualified", "Unqualified - Cannot teach this subject"),
                        ],
                        default="proficient",
                        max_length=20,
                    ),
                ),
                (
                    "years_taught",
                    models.IntegerField(
                        default=0,
                        help_text="How many years has this teacher taught this subject",
                    ),
                ),
                (
                    "last_taught_semester",
                    models.CharField(
                        blank=True,
                        help_text="When did they last teach this subject",
                        max_length=20,
                    ),
                ),
                (
                    "max_sessions_for_subject",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum sessions per week for this subject",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this assignment"
                    ),
                ),
                (
                    "priority_score",
                    models.FloatField(
                        default=0.0, help_text="Calculated priority for assignment"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable_app.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable_app.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority_score", "teacher__name"],
                "unique_together": {("teacher", "subject")},
            },
        ),
    ]
