# Generated by Django 5.2.6 on 2025-09-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "timetable_app",
            "0002_teacher_experience_years_teacher_specialization_and_more",
        ),
    ]

    operations = []
