# Generated by Django 5.2.6 on 2025-09-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable_app", "0006_fix_timeslot_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Configuration name (e.g., Semester 1 2024)",
                        max_length=100,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Academic year (e.g., 2024-25)", max_length=20
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        help_text="Semester (e.g., Odd/Even)", max_length=20
                    ),
                ),
                (
                    "college_start_time",
                    models.TimeField(
                        default="09:00:00", help_text="College start time"
                    ),
                ),
                (
                    "college_end_time",
                    models.TimeField(default="17:45:00", help_text="College end time"),
                ),
                (
                    "lunch_start_time",
                    models.TimeField(default="13:00:00", help_text="Lunch break start"),
                ),
                (
                    "lunch_end_time",
                    models.TimeField(default="13:45:00", help_text="Lunch break end"),
                ),
                (
                    "project_half_days_per_week",
                    models.IntegerField(
                        default=1, help_text="Number of half-days for project work"
                    ),
                ),
                (
                    "project_day_preference",
                    models.CharField(
                        choices=[
                            ("friday_afternoon", "Friday Afternoon"),
                            ("thursday_afternoon", "Thursday Afternoon"),
                            ("wednesday_afternoon", "Wednesday Afternoon"),
                            ("flexible", "Flexible - Algorithm decides"),
                        ],
                        default="friday_afternoon",
                        max_length=20,
                    ),
                ),
                (
                    "max_sessions_per_teacher",
                    models.IntegerField(
                        default=14, help_text="Maximum sessions per teacher per week"
                    ),
                ),
                (
                    "min_sessions_per_teacher",
                    models.IntegerField(
                        default=8, help_text="Minimum sessions per teacher per week"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Active configuration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={"ordering": ["day", "slot_number"]},
        ),
        migrations.AlterField(
            model_name="subject",
            name="sessions_per_week",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="day",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="slot_number",
            field=models.IntegerField(help_text="Slot position in day (1-9)"),
        ),
        migrations.DeleteModel(
            name="ProjectTimeAllocation",
        ),
    ]
