# Generated by Django 5.2.6 on 2025-09-30 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable_app", "0007_timetableconfiguration_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTimeAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("mini", "Mini Project"),
                            ("major", "Major Project"),
                            ("both", "Both Mini and Major"),
                        ],
                        default="mini",
                        max_length=10,
                    ),
                ),
                (
                    "preferred_day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                        ],
                        default="friday",
                        max_length=10,
                    ),
                ),
                (
                    "time_preference",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (First Half)"),
                            ("afternoon", "Afternoon (Second Half)"),
                            ("full_day", "Full Day"),
                        ],
                        default="afternoon",
                        max_length=15,
                    ),
                ),
                (
                    "hours_per_week",
                    models.IntegerField(
                        default=4, help_text="Hours allocated per week for projects"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable_app.division",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable_app.year",
                    ),
                ),
            ],
            options={
                "unique_together": {("year", "division", "project_type")},
            },
        ),
    ]
