# Generated by Django 5.2.6 on 2025-10-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetable_app", "0008_projecttimeallocation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teachersubjectpreference",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="teachersubjectpreference",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="teachersubjectpreference",
            name="teacher",
        ),
        migrations.DeleteModel(
            name="SubjectAllocationHistory",
        ),
        migrations.DeleteModel(
            name="TeacherSubjectPreference",
        ),
    ]
