# Generated by Django 5.2.6 on 2025-10-01 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timetable_app",
            "0009_alter_teachersubjectpreference_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("incharge_name", models.CharField(blank=True, max_length=100)),
                ("incharge_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="division",
            name="created_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="division",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="department_name",
            field=models.CharField(default="Information Technology", max_length=100),
        ),
        migrations.AlterField(
            model_name="division",
            name="num_batches",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterUniqueTogether(
            name="division",
            unique_together={("year", "name")},
        ),
        migrations.AddField(
            model_name="year",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable_app.department",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable_app.department",
            ),
        ),
    ]
