# Generated by Django 5.2.6 on 2025-10-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timetable_app",
            "0010_department_division_created_date_division_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.CharField(default="Information Technology", max_length=100),
        ),
        migrations.RemoveField(
            model_name="year",
            name="department",
        ),
        migrations.AlterUniqueTogether(
            name="division",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="department_name",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.RemoveField(
            model_name="division",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="division",
            name="is_active",
        ),
    ]
