# Generated by Django 5.2.6 on 2025-10-02 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timetable_app",
            "0011_alter_teacher_department_remove_year_department_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("break_start_time", models.TimeField(default="13:00")),
                ("break_end_time", models.TimeField(default="13:45")),
                ("max_sessions_per_teacher_per_week", models.IntegerField(default=14)),
                ("min_sessions_per_teacher_per_week", models.IntegerField(default=10)),
                ("default_lab_duration_hours", models.IntegerField(default=2)),
                ("allow_cross_year_lab_conflicts", models.BooleanField(default=False)),
                ("remedial_lectures_per_week", models.IntegerField(default=1)),
                (
                    "remedial_preferred_time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("either", "Either"),
                        ],
                        default="afternoon",
                        max_length=20,
                    ),
                ),
                ("project_time_slots_per_week", models.IntegerField(default=2)),
                (
                    "morning_afternoon_balance_percentage",
                    models.IntegerField(default=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="lab_frequency_per_week",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="subject",
            name="lecture_duration_hours",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="subject",
            name="requires_remedial",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="RemedialLecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("any", "Any Day"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("either", "Either"),
                        ],
                        default="afternoon",
                        max_length=20,
                    ),
                ),
                ("is_scheduled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable_app.division",
                    ),
                ),
                (
                    "scheduled_timeslot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable_app.timeslot",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable_app.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable_app.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remedial Lecture",
                "verbose_name_plural": "Remedial Lectures",
                "unique_together": {("subject", "division")},
            },
        ),
    ]
