# Generated by Django 5.2.6 on 2025-10-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable_app", "0012_systemconfiguration_room_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="student_count",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="lab",
            name="available_equipment",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="room",
            name="available_equipment",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="subject",
            name="equipment_requirements",
            field=models.JSONField(default=list),
        ),
    ]
